save_loc: "semdedup"
clusters_per_job: 200
embs_memory_loc: "emb.npy"
dataset_size: 527678
emd_size: 384
num_clusters: 200
sorted_clusters_path: "sorted_clusters"
which_to_keep: "hard"
seed: 1234
eps_list:
  - 0.7
  - 0.8
  - 0.9
  # - 0.05
  # - 0.1
largest_cluster_size_to_process: 10000000
